// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddProject(arg1:string,arg2:string):Promise<models.Project>;

export function CreateSnapshot(arg1:string,arg2:string,arg3:string):Promise<models.Snapshot>;

export function DeleteSnapshot(arg1:string):Promise<void>;

export function EstimateSnapshotSize(arg1:string):Promise<number>;

export function GetAppSettings():Promise<models.AppSettings>;

export function GetChangeSummary(arg1:string):Promise<models.ChangeSummary>;

export function GetProject(arg1:string):Promise<models.Project>;

export function GetProjectStats(arg1:string):Promise<Record<string, any>>;

export function GetRestorePreview(arg1:string):Promise<models.RestorePreview>;

export function GetSnapshot(arg1:string):Promise<models.Snapshot>;

export function GetSnapshotEntries(arg1:string):Promise<Array<models.SnapshotEntry>>;

export function ListProjects():Promise<Array<models.Project>>;

export function ListSnapshots(arg1:string):Promise<Array<models.Snapshot>>;

export function OpenProjectFolder(arg1:string):Promise<void>;

export function RemoveProject(arg1:string):Promise<void>;

export function RenameSnapshot(arg1:string,arg2:string):Promise<void>;

export function RestoreSnapshot(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectVaultDirectory():Promise<string>;

export function SetSnapshotPinned(arg1:string,arg2:boolean):Promise<void>;

export function SetVaultRoot(arg1:string):Promise<void>;

export function UpdateProject(arg1:string,arg2:string,arg3:Array<string>):Promise<models.Project>;

export function UpdateSnapshotNotes(arg1:string,arg2:string):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;

export function WindowToggleMaximize():Promise<void>;
