// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1, arg2) {
  return window['go']['main']['App']['AddProject'](arg1, arg2);
}

export function CreateSnapshot(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSnapshot'](arg1, arg2, arg3);
}

export function DeleteSnapshot(arg1) {
  return window['go']['main']['App']['DeleteSnapshot'](arg1);
}

export function EstimateSnapshotSize(arg1) {
  return window['go']['main']['App']['EstimateSnapshotSize'](arg1);
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetChangeSummary(arg1) {
  return window['go']['main']['App']['GetChangeSummary'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjectStats(arg1) {
  return window['go']['main']['App']['GetProjectStats'](arg1);
}

export function GetRestorePreview(arg1) {
  return window['go']['main']['App']['GetRestorePreview'](arg1);
}

export function GetSnapshot(arg1) {
  return window['go']['main']['App']['GetSnapshot'](arg1);
}

export function GetSnapshotEntries(arg1) {
  return window['go']['main']['App']['GetSnapshotEntries'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListSnapshots(arg1) {
  return window['go']['main']['App']['ListSnapshots'](arg1);
}

export function OpenProjectFolder(arg1) {
  return window['go']['main']['App']['OpenProjectFolder'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RenameSnapshot(arg1, arg2) {
  return window['go']['main']['App']['RenameSnapshot'](arg1, arg2);
}

export function RestoreSnapshot(arg1) {
  return window['go']['main']['App']['RestoreSnapshot'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectVaultDirectory() {
  return window['go']['main']['App']['SelectVaultDirectory']();
}

export function SetSnapshotPinned(arg1, arg2) {
  return window['go']['main']['App']['SetSnapshotPinned'](arg1, arg2);
}

export function SetVaultRoot(arg1) {
  return window['go']['main']['App']['SetVaultRoot'](arg1);
}

export function UpdateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3);
}

export function UpdateSnapshotNotes(arg1, arg2) {
  return window['go']['main']['App']['UpdateSnapshotNotes'](arg1, arg2);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMaximize() {
  return window['go']['main']['App']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WindowToggleMaximize() {
  return window['go']['main']['App']['WindowToggleMaximize']();
}
